table:
  name: rooms
  schema: public
object_relationships:
  - name: hotel
    using:
      foreign_key_constraint_on: hotel_id
  - name: room_type
    using:
      foreign_key_constraint_on: room_type_id
  - name: images
    using:
      foreign_key_constraint_on:
        table:
          name: room_images
          schema: public
        columns:
          - room_id
insert_permissions:
  - role: landlord
    permission:
      check:
        hotel_id:
          _in: X-Hasura-Hotel-Ids
      columns:
        - hotel_id
        - room_number
        - room_type_id
        - price_night
        - capacity
        - is_available
        - image_urls
update_permissions:
  - role: landlord
    permission:
      filter:
        hotel_id:
          _in: X-Hasura-Hotel-Ids
      columns:
        - room_number
        - room_type_id
        - price_night
        - capacity
        - is_available
        - image_urls
      check:
        hotel_id:
          _in: X-Hasura-Hotel-Ids
delete_permissions:
  - role: landlord
    permission:
      filter:
        hotel_id:
          _in: X-Hasura-Hotel-Ids
select_permissions:
  - role: tenant
    permission:
      columns:
        - room_id
        - hotel_id
        - room_number
        - room_type_id
        - price_night
        - capacity
        - status
        - is_available
        - image_urls
        - created_at
        - updated_at
      filter: {}
  - role: landlord
    permission:
      columns:
        - room_id
        - hotel_id
        - room_number
        - room_type_id
        - price_night
        - capacity
        - status
        - is_available
        - image_urls
        - created_at
        - updated_at
      filter: {}
